add support to claat2 for retrieving assets from a global location
googlecodelabs/tools pull request #152
Opened 2019-02-04 15:05 UTC by marcacohen

2019-02-04 16:03 UTC, shawnbuso commented on claat/render/template-elements.html
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Code+Pro:400|Roboto:400,300,400italic,500,700|Roboto+Mono">
Same question here as the other PR - does this break if we leave it as just "//"?

2019-02-07 17:09 UTC, shawnbuso approved these changes

2019-02-07 17:20 UTC, merged

2025-11-04 23:19 UTC, Mike29CZ requested changes
Mike

2025-11-04 23:19 UTC, Mike29CZ approved these changes

2025-11-04 23:20 UTC, Mike29CZ approved these changes

2025-11-04 23:20 UTC, Mike29CZ requested changes
- @