Add support for language hint in code blocks and console blocks
googlecodelabs/tools pull request #463
Opened 2020-09-16 00:46 UTC by nicolasgarnier

Add support for language hint in code blocks aka:

```
```go
...
`` `
```

Add support for Console blocks (no syntax highlighting and no special Code block features in devsite). You can get these code blocks when using the consolas font in HTML or when using 

```
```console
...
`` `
```

2020-09-16 00:56 UTC, nicolasgarnier commented
Will fix b/168655623 and b/168655623

2020-09-16 06:30 UTC, DragonRider0o0 approved these changes

2020-09-16 06:34 UTC, DragonRider0o0 requested changes
Please fix travis build errors.

2020-09-16 07:48 UTC, nicolasgarnier commented
Travis is passing but please do not merge. I discovered a regression. This requires some more investigating.

2020-09-16 15:44 UTC, nicolasgarnier commented
Done. Please merge :)

2020-09-17 17:04 UTC, DragonRider0o0 approved these changes

2020-09-17 17:04 UTC, merged