Fix bug with image bytes length detection.
googlecodelabs/tools pull request #719
Opened 2022-03-22 17:30 UTC by shawnbuso

2022-03-22 17:41 UTC, cassierecher requested changes

2022-03-22 17:41 UTC, cassierecher commented on claat/fetch/fetch.go
> +        if string(b[6:10]) == "JFIF" {
Use `switch` instead

2022-03-22 18:11 UTC, DragonRider0o0 approved these changes

2022-03-24 21:21 UTC, shawnbuso commented
Requested changes have been made.

2022-04-04 18:18 UTC, cassierecher approved these changes

2022-04-05 14:49 UTC, merged